import { Comfortaa } from "next/font/google";
import "./globals.css";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  display: "swap",
});



export const metadata = {
  title: "HMPS SI",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" translate="no">
      <body
        className={`${comfortaa.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
